### ISSUE TITLE
Filter dumped block of memory

### ISSUE THREAD

**Issue by adrix89** [MX-Futhark/hook-any-text#23]
I have a game that dumps lines into one block of memory so the previous text remains while only the new line is refreshed.
The output is something like this:

```
——悪党だけを狙って盗みを行う義賊。
怪盗トゥエルブだ。
----------
れてしまって……、
私一人だけが取り残されたの。
----------
�=iT
```
The first text has no problem and if i could filter out everything after `-----` it would be perfect but I tried with regex and haven't managed.
What does `-----` represent in regex for the tool?

**Comment by MX-Futhark** [comment]
Hello,

When you select a block of memory in Cheat Engine, HAT does two things (mainly):

- Remove inconvertible hex data from the selection
- Convert all bits of convertible hex data into text. The `----` separation represents an area of inconvertible data/garbage.

I originally implemented this because in some games I used for testing, memory areas representing text were separated by areas of `0x00`s and this formatting was working neatly.

Note that you cannot catch these dashes with a replacement regex because they are displayed after all replacements happen. They are just a formatting information. However you can write your own program that listens for changes in the clipboard and trims out everything after `----------`.

What you would need to achieve this from HAT is an option to only take the first garbage-free memory region into account and display that. Because of this I'm going to treat this issue as a low-priority feature request as it doesn't prevent you from actually accessing the text you need.

**Comment by adrix89** [comment]
I actually managed to filter it after some fiddling.
What I did is use regex in hex2hex with the expression:
`((?:[0-9A-Fa-fx]{2})+?)00.+`
The game treats `00` as the string termination.
It was a bit tricky since hex comes in pairs and you can get thing like `f0 0a` but that expression works.

I guess thanks for having the hex2hex option.
Also is it me or does the hex input has a `0x` at the start? It shows in the debugging options? This might mess with hex filtering.

**Comment by MX-Futhark** [comment]
Glad you could find a way =) And no, hex inputs are not actually prefixed by `0x`, this is only a visual cue for debugging. I'm closing this issue now.
