### ISSUE TITLE
Double charset detection

### ISSUE THREAD

**Issue by adrix89** [MX-Futhark/hook-any-text#24]
Some games have double charset encoding like ASCII with Shift+JS
Like in this text:
```
BGMの音量を
調節します
```
Currently in HAT the BGM gets removed.
It would be nice if we could detect both encodings.

**Comment by MX-Futhark** [comment]
Wow that's one hell of an edge case.

Unfortunately the converter simply doesn't allow for that. In order to detect the encoding HAT attempts to convert the hexadecimal data into all supported encodings and for each, it strips hex patterns that cannot happen in said encoding. And we have the added complexity of hex/string replacements to take into account.

Although theoretically possible with enough contextual information, multi-encoding detection will not be implemented unless someone opens a pull request with this feature because it's an unreasonable time/effort/added value investment.
