### ISSUE TITLE
Lua engine error at startup

### ISSUE THREAD

**Issue by orangebirddave** [MX-Futhark/hook-any-text#29]
Hello, I'm trying to use HAT 1.0.0 with Cheat Engine 7.3, and I immediately get this error on startup. When I try to CTRL+B an address and select a region, nothing happens on HAT and it doesn't show up in the selections. I've tried reinstalling everything including Java and tried using HAT 0.9.0 but I still get the same error. 

![image](https://user-images.githubusercontent.com/78650178/131009091-de77f457-64b3-4821-92cd-9f2d92471963.png)
Error in native thread called Unnamed::...am Files\Cheat Engine 7.3\autorun\selectionConverter.lua:25: attempt to call a nil value (local 'evaluatedFunction')

**Comment by MX-Futhark** [comment]
Hello and sorry for the inconvenience.

Unfortunately I cannot reproduce on my computer with Cheat Engine 7.3 so I’ll need your assistance to determine the root cause of the problem.

First, **which version of Java are you using**?

Second, please follow these instructions:
1. Delete this folder if it exists: `C:\Users\<Your name>\AppData\Local\Temp\HookAnyText` (note that the `AppData` folder is hidden, so you’ll have to either change your settings to show hidden folders, or access it by inputing the path textually in Windows Explorer)
2. Delete this folder if it exists: `C:\Users\<Your name>\AppData\Roaming\HookAnyText` (same remark)
3. In `C:\Program Files\Cheat Engine 7.3\autorun\selectionConverter.lua`, please replace [lines 174 through 177](https://github.com/MX-Futhark/hook-any-text/blob/3007b65c63e119fc7101c899e93b52675e7b0c95/src/main/lua/selectionConverter.lua#L174) with the following (You will need to run your text editor in Administrator mode for that):
```lua
local keyValueCouples = f:read("*all")
print(keyValueCouples)
for k, v in string.gmatch(keyValueCouples, "([%w_]+)=([^\r\n]+)") do
	-- Config[k] = Helpers.evalExpression(v) or v
end
```
4. Restart Cheat Engine; it will show a popup much like the one you get with the error message. **What does it say in the `Output` field**?

Thank you in advance.

**Comment by orangebirddave** [comment]
I'm using Java Version 8 Update 301
![image](https://user-images.githubusercontent.com/78650178/131246753-89a8b7a0-4b3e-45ed-ba08-a894052bde1d.png)

After following these steps I get the same message
![image](https://user-images.githubusercontent.com/78650178/131247016-303123f4-c3ce-443e-a56a-b2b365139aee.png)

**Comment by MX-Futhark** [comment]
The modifications I asked you to apply to selectionConverter.lua are meant to suppress this error. Are you sure the file was properly saved? Again, you will need to edit the file in admin mode.

**Comment by orangebirddave** [comment]
Oh, I'm sorry, for some reason notepad++ didn't actually save the file. I tried it again and now I get this:

![image](https://user-images.githubusercontent.com/78650178/131247820-e884bd4f-aa9c-4676-bbaa-d939216573ec.png)

**Comment by MX-Futhark** [comment]
Oh I think I know what’s going on. Are you using a Turkish or Azeri locale?

**Comment by orangebirddave** [comment]
Oh, yeah my system locale is in Turkish, that's probably why some letters are showing up as question marks here, is that related to the first error I'm getting?

Edit: Oh yeah the error is gone after running it in Japanese with the Locale Emulator, but now it doesn't find the adresses when I attach it to my emulator (Ryujinx with Tsukihime Remake) and search the text converted to hex.
I can't seem to run the 64bit Cheat Engine exe with the Locale Emulator so I tried the 32bit one so I'm assuming that's the problem?
I'm gonna try changing the system locale of my pc and try again

**Comment by MX-Futhark** [comment]
Yup, what you are seeing on screen is the textual version of the default configuration of hook-any-text, and it sometimes needs to switch between lowercase and uppercase internally (e.g. `stabilization-threshold` becomes `STABILIZATION_THRESHOLD`).

However the lower/uppercase conversion is locale-dependent by default, and I completely forgot to force it to English. Therefore `stabilization-threshold` becomes `STABİLİZATİON_THRESHOLD` on locales for which there is a distinction between dotted i and dotless i, which causes the program to break. The fact that I’m working in ASCII in this case makes matters worse since the uppercase dotted i is not properly encoded, hence the question marks.

You should be able to bypass the issue by following these instructions:
1. Use a locale agnostic to dotted/dotless i (i.e. anything except Turkish and Azeri)
2. Remove `C:\Users\<Your name>\AppData\Local\Temp\HookAnyText` and `C:\Users\<Your name>\AppData\Roaming\HookAnyText` again
3. Restore `C:\Program Files\Cheat Engine 7.3\autorun\selectionConverter.lua` to [its previous state](https://raw.githubusercontent.com/MX-Futhark/hook-any-text/3007b65c63e119fc7101c899e93b52675e7b0c95/src/main/lua/selectionConverter.lua).

I’m not familiar with Locale Emulator so I can’t vouch for that, but otherwise that should do the trick.

I’ll fix the case conversion issue when I can and let you know when it’s done. Hopefully in the coming week but I haven’t worked on this project in two years and need to set things up again + I have a fulltime job, so no promises.

Thank you for reporting the issue and for your assistance =)

**Comment by orangebirddave** [comment]
Oh yeah changing the locale and the language, then running the 64bit exe works nicely, until the issue is fixed I'll just use it like that, thanks for the help!

**Comment by MX-Futhark** [comment]
This should be fixed now!

You can download the latest version [here](http://mx-futhark.github.io/hook-any-text/downloads/HookAnyText_v1.0.1.zip), extract the archive into Cheat Engine’s `autorun` folder, and set your system language back to Turkish.
